### ISSUE TITLE
Still working on this?

### ISSUE THREAD

**Issue by SirBeethoven** [MarcuzD/MM#2]
Are you still working on this wonderful project? :)

**Comment by MarcuzD** [comment]
Yes, I'm still working on it, just really slowly :stuck_out_tongue: 

http://gbatemp.net/profile-posts/45067/
http://gbatemp.net/threads/poll-help-marcusd-decide-what-to-port-next.435679/page-2#post-6557004

**Comment by MarcuzD** [comment]
Here's the first commit of my recent progress: https://github.com/MarcuzD/MM/commit/1f6f1d7dc362347de380c0ed7aab07cceddb6446
It's so big, that it freezes my browser :stuck_out_tongue_winking_eye:

**Comment by SirBeethoven** [comment]
OMG! That IS huge! It freezes mine too!
